version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "weekly", day: "monday", time: "06:00", timezone: "Africa/Johannesburg" }
    open-pull-requests-limit: 5
    labels: ["dependencies", "github-actions"]
    commit-message: { prefix: "chore", prefix-development: "chore", include: "scope" }
    target-branch: "main"
  - package-ecosystem: "npm"
    directory: "/"
    schedule: { interval: "weekly", day: "monday", time: "06:30", timezone: "Africa/Johannesburg" }
    open-pull-requests-limit: 5
    labels: ["dependencies", "javascript"]
    commit-message: { prefix: "chore", prefix-development: "chore", include: "scope" }
    target-branch: "main"
  - package-ecosystem: "docker"
    directory: "/"
    schedule: { interval: "weekly", day: "monday", time: "07:00", timezone: "Africa/Johannesburg" }
    open-pull-requests-limit: 5
    labels: ["dependencies", "container"]
    commit-message: { prefix: "chore", prefix-development: "chore", include: "scope" }
    target-branch: "main"
