name: Enforce Action Pinning
on:
  push:
    branches: [main]
    paths: [".github/workflows/**", ".github/actions/**"]
  pull_request:
    paths: [".github/workflows/**", ".github/actions/**"]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  check:
    permissions:
      contents: read
    uses: nabhold/shared/.github/workflows/enforce-action-pinning.yml@ad5cdb028023cd6b9c48cd8d7e6151ef4ab0cd73 # v1.0.0
