name: Enforce Dependabot Config
on:
  push:
    branches: [main]
    paths: [".github/dependabot.yml"]
  pull_request:
    paths: [".github/dependabot.yml"]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  check:
    permissions:
      contents: read
    uses: nabhold/shared/.github/workflows/enforce-dependabot-config.yml@ad5cdb028023cd6b9c48cd8d7e6151ef4ab0cd73 # v1.0.0
