name: Enforce Action Pinning
on:
  push:
    branches: [main]
    paths: [".github/workflows/**", ".github/actions/**"]
  pull_request:
    paths: [".github/workflows/**", ".github/actions/**"]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  check:
    permissions:
      contents: read
    uses: nabhold/shared/.github/workflows/enforce-action-pinning.yml@f8df9b90ffe8fef5cbf6d14a9bcf868f723d1464 # v1.1.0
