name: Enforce Action Pinning
on:
  push:
    branches: [main]
    paths: [".github/workflows/**", ".github/actions/**"]
  pull_request:
    paths: [".github/workflows/**", ".github/actions/**"]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  check:
    permissions:
      contents: read
    uses: nabhold/shared/.github/workflows/enforce-action-pinning.yml@38defb11aacd95a6f68b7db8026fe336417a2af6 # v1.2.0
