name: Enforce Dependabot Config
on:
  push:
    branches: [main]
    paths: [".github/dependabot.yml"]
  pull_request:
    paths: [".github/dependabot.yml"]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  check:
    permissions:
      contents: read
    uses: nabhold/shared/.github/workflows/enforce-dependabot-config.yml@38defb11aacd95a6f68b7db8026fe336417a2af6 # v1.2.0
