name: Security
on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:
permissions:
  contents: read
jobs:
  codeql:
    permissions:
      contents: read
      security-events: write
      actions: read
    uses: nabhold/shared/.github/workflows/security-codeql.yml@498c431ea7eb76eb038975bc49e7087499d30d48 # shared main, verified 2026-08-30
    with:
      languages: '["javascript-typescript"]'
